# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kr8 < Formula
  desc "An opinionated configuration management tool for Kubernetes Clusters"
  homepage "https://ice-bergtech.github.io/kr8"
  version "0.1.0"
  license "MIT"

  depends_on "helm"
  depends_on "jsonnet"

  on_macos do
    url "https://github.com/ice-bergtech/kr8/releases/download/v0.1.0/kr8_0.1.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy,
      headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_TAP_GITHUB_TOKEN"]}"
      ]
    sha256 "cf58f39274b13c1586021b1e35aa99afca3af1d4a7f154ea78b815b3a2d79d19"

    def install
      bin.install "kr8"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kr8
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ice-bergtech/kr8/releases/download/v0.1.0/kr8_0.1.0_linux_amd64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_TAP_GITHUB_TOKEN"]}"
          ]
        sha256 "a229401d64a177ea1b3762f92bfed9fe863544418854c9e2942fbab87bd8fca4"

        def install
          bin.install "kr8"
        end
      end
    end
  end
end
