# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kr8 < Formula
  desc "An opinionated configuration management tool for Kubernetes Clusters"
  homepage "https://ice-bergtech.github.io/kr8"
  version "0.2.3"
  license "MIT"

  depends_on "helm"
  depends_on "jsonnet"

  on_macos do
    url "https://github.com/ice-bergtech/kr8/releases/download/v0.2.3/kr8_0.2.3_darwin_amd64.tar.gz", using: CurlDownloadStrategy,
      headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_TAP_GITHUB_TOKEN"]}"
      ]
    sha256 "b35059bb096b11952b624b7a975a1adb8de4153a0bfa7af746640e3f4ef3e6b3"

    def install
      bin.install "kr8"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kr8
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ice-bergtech/kr8/releases/download/v0.2.3/kr8_0.2.3_linux_amd64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_TAP_GITHUB_TOKEN"]}"
        ]
      sha256 "3886105332fdf385f0e155b5a46cab627e0818694db74279e5e1c645b0900f11"
      def install
        bin.install "kr8"
      end
    end
  end
end
