# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kr8 < Formula
  desc "An opinionated configuration management tool for Kubernetes Clusters"
  homepage "https://ice-bergtech.github.io/kr8"
  version "0.0.8"
  license "MIT"

  depends_on "helm"
  depends_on "jsonnet"

  on_macos do
    url "https://github.com/ice-bergtech/kr8/releases/download/v0.0.8/kr8_0.0.8_darwin_amd64.tar.gz", using: CurlDownloadStrategy,
      headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_TAP_GITHUB_TOKEN"]}"
      ]
    sha256 "14153cc1b5d34f0c06358f2b80056582754cd1e47610e774954895a40170acfe"

    def install
      bin.install "kr8"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kr8
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ice-bergtech/kr8/releases/download/v0.0.8/kr8_0.0.8_linux_amd64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_TAP_GITHUB_TOKEN"]}"
          ]
        sha256 "e337fdfb9f6829573d11f53d4e6d8e004e43e0b2cd571f6750823f47cd383c5c"

        def install
          bin.install "kr8"
        end
      end
    end
  end
end
